#!/usr/bin/env bash
# Install and config ufw firewall to block all incoming traffic except for TCP ports 22, 443 and 80.

sudo apt-get -y install ufw
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
